MEMORY
{
  FLASH : ORIGIN = 0x00000000, LENGTH = 256K
  RAM : ORIGIN = 0x20000000, LENGTH = 64K
}

SECTIONS {
  linkme_SHENANIGANS : { *(linkme_SHENANIGANS) } > FLASH
  linkme_EMPTY : { *(linkme_EMPTY) } > FLASH
}
INSERT BEFORE .rodata
